version: 2
jobs:
  build:
    working_directory: ~/BackEnd
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "BackEnd/pom.xml" }}

      - run: mvn -f BackEnd/pom.xml dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2S
          key: circleci-demo-java-spring-{{ checksum "BackEnd/pom.xml" }}

      - run: mvn -f BackEnd/pom.xml package

      - store_test_results:
          path: BackEnd/target/surefire-reports

      - store_artifacts:
          path: BackEnd/target/monday-1530-2-0.0.1-SNAPSHOT.jar